
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Aug 16 21:21:15 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 25;
  public static final int LBRACKET = 28;
  public static final int CONST = 5;
  public static final int YIELD = 48;
  public static final int SLASH = 44;
  public static final int NUMCONST = 50;
  public static final int CASE = 46;
  public static final int NOTEQUAL = 18;
  public static final int CONTINUE = 36;
  public static final int LPAREN = 10;
  public static final int GREATER = 19;
  public static final int SEMI = 8;
  public static final int LESS = 21;
  public static final int MINUS = 13;
  public static final int MULVECTOR = 54;
  public static final int STAR = 14;
  public static final int RPAREN = 11;
  public static final int AND = 23;
  public static final int LESSEQUAL = 22;
  public static final int OR = 24;
  public static final int COMMA = 7;
  public static final int CLASS = 40;
  public static final int PLUS = 12;
  public static final int IF = 32;
  public static final int DOT = 27;
  public static final int EOF = 0;
  public static final int RETURN = 37;
  public static final int MINUSMINUS = 26;
  public static final int RBRACKET = 29;
  public static final int EQUAL = 6;
  public static final int NEW = 39;
  public static final int error = 1;
  public static final int ISEQUAL = 17;
  public static final int CHARCONSTANT = 52;
  public static final int PERCENT = 16;
  public static final int IDENT = 53;
  public static final int BREAK = 35;
  public static final int VOID = 45;
  public static final int SWITCH = 34;
  public static final int GREATEREQUAL = 20;
  public static final int COLON = 31;
  public static final int ELSE = 42;
  public static final int LBRACE = 3;
  public static final int ENUM = 41;
  public static final int READ = 38;
  public static final int SLASHS = 15;
  public static final int WHILE = 47;
  public static final int QUEST = 30;
  public static final int DEFAULT = 49;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 51;
  public static final int EXTENDS = 43;
  public static final int PROG = 2;
  public static final int PRINT = 9;
  public static final int DO = 33;
}

